services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - ghost_network

  ghost:
    image: ghost:latest
    environment:
      NODE_ENV: development
      url: https://andromeda.local
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    volumes:
      - ./docker/ghost:/var/lib/ghost/content
    networks:
      - ghost_network

  node:
    image: node:22
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    networks:
      - ghost_network

networks:
  ghost_network:
